#configures application name
application: udacity-cs253
#Version of the code
version: 1
#Uses Python 2.7 
runtime: python27
#Api version
api_version: 1
#Sets threadsafe to true
threadsafe: true

#Handlers for URL
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: blog.app

#Imports jinja library(code structure library
libraries:
- name: jinja2
  version: latest

#Python image library 
- name: PIL
  version: "1.1.7"
